version: '3'
services:
  git:
    build: ./git-simple-http
  nginx:
    build: ./nginx
    ports:
    - "${PORT:-8888}:80"
    depends_on:
    - git
    - whisper
  mongo:
    image: mongo
  whisper:
    build: ..
    environment:
      PUBLIC_HOSTNAME: "${PUBLIC_HOSTNAME}"
      MONGO_DB_URL: "mongodb://mongo:27017/CodeWhispers"
    depends_on:
    - mongo
    - git
