version: '3'
services:
  git:
    build: ./git-simple-http
  nginx:
    build: ./nginx
    ports:
    - "8888:80"
    depends_on:
    - git
    - whisper
  mongo:
    image: mongo
  whisper:
    build: ..
    environment:
      PUBLIC_HOSTNAME: "${PUBLIC_HOSTNAME}"
    depends_on:
    - mongo
    - git
